### ISSUE TITLE
Add concurrency support

### ISSUE THREAD

**Issue by kevinmarrec** [Akryum/monorepo-run#5]
It would be nice having something like https://github.com/lerna/lerna/tree/master/core/global-options#--concurrency.

EDIT: Overall the use case would be to have build by build outputs instead of having parallel outputs when using `mono-run build` for example.

Just close if not relevant.

**Comment by Akryum** [comment]
Currently mono-run creates one thread per task, so they are all executed in parallel. Your usecase would be to limit the number of parallel tasks run at the same time?

**Comment by kevinmarrec** [comment]
@Akryum Indeed that's it
